### ISSUE TITLE
[Idea] Function to look for files which can potentially have the license

### ISSUE THREAD

**Issue by giordano** [ericphanson/LicenseCheck.jl#2]
I'm not even sure this function belongs here, but I'm throwing this idea anyway.  As far as I understand, `licensecheck` reads the content of a file and tries to determine whether it matches a known license.  The problem is that often you need first to find the license file.  Unless you plan to open all files in a directory, I suggest to have a function which looks for files with names usually employed by license files (case insensitive):
```
COPYING
COPYRIGHT
LICENCE
LICENSE
NOTICE
...
```
plus all possible combinations with extensions like `.txt`, `.md`, `.rst`.  Sometimes license files have the name of the license, like `GPL.txt`, or `GPL-2.0.txt`.

**Comment by ericphanson** [comment]
Yeah, that sounds useful. Probably that function would have to be duplicated by most users of LicenseCheck if it doesn't exist here, so this is a good place for it.

We could re-use the list of names in `OSI_LICENSES` for things like GPL.txt, though that will only work if the license is OSI approved and the name they use is the SPDX identifier.

A kind of wild idea would be to just try every plaintext toplevel file and take whichever one has the highest `percent_covered`. That seems like it would be pretty comprehensive but could take awhile if for some reason there were many top-level files, or if there were really big files (which could cause `licensecheck` to be slow).
